import React, { useState, useEffect } from 'react';
import GetPrompt from './GetPrompt'; // Update the path as needed

function Earth() {
  const [earthData, setEarthData] = useState("");

  useEffect(() => {
    const fetchData = async () => {
      try {
        // Use the GetPrompt function instead of the fetch function
        const response = await GetPrompt("give me information about Earth");

        // Update the state with the fetched data
        setEarthData(response.data.choices[0].message.content);
      } catch (error) {
        console.error("Error making the request:", error);
      }
    };

    // Call the fetchData function
    fetchData();
  }, []); // Empty dependency array to ensure the effect runs only once

  return (
    <div className='border-2 border-dark rounded5'>
      <h1 className='text-black'>Name: Earth</h1>
      <p className='text-dark'>Earth, the third planet from the Sun in our solar system, is a unique and vibrant celestial body. With a diameter of approximately 12,742 kilometers and a mass of about 5.97 x 10^24 kilograms, it is distinguished by its life-supporting environment, featuring a solid core, liquid outer core, rocky mantle, and thin crust. The atmosphere, predominantly composed of nitrogen and oxygen, envelops the planet and sustains a rich tapestry of life.

Often referred to as the "Blue Planet," Earth is characterized by vast bodies of water, covering around 71% of its surface. This abundance of water contributes to diverse ecosystems and supports a myriad of plant and animal species, creating a dynamic and interconnected web of life.

Earth experiences a wide range of climates, from polar ice caps to tropical rainforests, influenced by factors such as geography and atmospheric conditions. The planet's rotation on its axis results in day and night cycles, while its orbit around the Sun defines the passage of seasons.

The magnetic field generated by Earth's molten core acts as a protective shield, deflecting solar winds and cosmic radiation. The surface features distinct continents, each with its own geography and characteristics. Human civilization has flourished on Earth, giving rise to diverse cultures, languages, and technological advancements.

While Earth's natural beauty and biodiversity are extraordinary, it faces environmental challenges such as climate change, pollution, and habitat loss. Global efforts are underway to address these challenges and promote responsible environmental stewardship.

As a resident of our solar system, Earth plays a crucial role in the delicate cosmic dance of celestial bodies. Ongoing scientific exploration and environmental awareness are essential to understanding, preserving, and sustaining the intricate balance of life on this remarkable planet.






</p>
    </div>
  );
}

export default Earth;
